name: minfin_login
description: Minfin proyektlarida O'zbekiston yoki chet eldan kirishni ajratishni bilish uchun kerak
version: 0.0.8
homepage: https://github.com/abbos2101/minfin_login

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_lints: ^2.0.1
